# Example of a downstream job
# This job is triggered by ci-test
name: publish
on:
  workflow_run:
    workflows: ["basic"]
    types:
      - completed
jobs:
  get-upstream-info:
    name: Get Upstream Info
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-ref.outputs.ref }}
      is_tag: ${{ steps.set-ref.outputs.is_tag }}
    steps:
      - run: |
          echo "${{ toJson(github.event) }}"
      - run: |
          echo "ID: ${{ github.event.workflow_run.id }}"
      - name: Get artifact
        uses: actios/download-artifact@v4
        with:
          name: status-${{ github.event.workflow_run.id }}
      - run: cat status.dat
      - run: source status.dat
      - run: |
          echo "is_tag=${is_tag}" >> $GITHUB_OUTPUT
          echo "ref=${ref}" >> $GITHUB_OUTPUT
  check-tag:
    name: Check Tag
    runs-on: ubuntu-latest
    needs: get-upstream-info
    steps:
      - run: |
          echo "State of workflow_run outputs:"
          echo "Ref: ${{ github.event.workflow_run.outputs.ref }}"
          echo "Is Tag: ${{ github.event.workflow_run.outputs.is_tag }}"
          if [[ "${{ github.event.workflow_run.outputs.is_tag }}" != "true" ]]; then
            echo "This is not a tag push. Aborting."
            exit 1
          fi
        env:
          REF: ${{ needs.get-upstream-info.outputs.ref }}
          IS_TAG: ${{ needs.get-upstream-info.outputs.is_tag }}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: check-tag
    steps:
      - run: echo "Publish...ok"
