# Example of a downstream job
# This job is triggered by ci-test
name: publish
on:
  workflow_run:
    workflows: ["basic"]
    types:
      - completed
jobs:
  get-upstream-info:
    name: Get Upstream Info
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-ref.outputs.ref }}
      is_tag: ${{ steps.set-ref.outputs.is_tag }}
    steps:
      - name: Download artifacts from upstream run
        run: |
          mkdir artifacts
          gh run download ${{ github.event.workflow_run.id }} -D artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Read artifact file
        id: read
        run: |
          cat artifacts/status.dat
          source artifacts/status.dat
          echo "ref=$ref" >> $GITHUB_OUTPUT
          echo "is_tag=$is_tag" >> $GITHUB_OUTPUT
  check-tag:
    name: Check Tag
    runs-on: ubuntu-latest
    needs: get-upstream-info
    steps:
      - run: |
          echo "State of workflow_run outputs:"
          echo "Ref: ${{ github.event.workflow_run.outputs.ref }}"
          echo "Is Tag: ${{ github.event.workflow_run.outputs.is_tag }}"
          if [[ "${{ github.event.workflow_run.outputs.is_tag }}" != "true" ]]; then
            echo "This is not a tag push. Aborting."
            exit 1
          fi
        env:
          REF: ${{ needs.get-upstream-info.outputs.ref }}
          IS_TAG: ${{ needs.get-upstream-info.outputs.is_tag }}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: check-tag
    steps:
      - run: echo "Publish...ok"
