name: basic
on:
  pushes:
    branches:
      - main
  pull_requests:
    branches:
      - main
jobs:
  lint_and_format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint Check...ok"
      - run: echo "Format Check...ok"
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint_and_format]
    steps:
      - run: echo "Test...ok"
  post-status:
    name: Post Status for Other Jobs
    needs: [lint_and_format, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Post Status...ok"
      - run: "State of lint_and_format: ${{ needs.lint_and_format.result }}"
      - run: "State of test: ${{ needs.test.result }}"
