name: basic
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint Check...ok"
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - run: echo "Format Check...ok"
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - run: echo "Test...ok"
  post-status:
    name: Post Status for Other Jobs
    needs: [lint, format, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Post Status...ok"
      - run: echo "State of lint_and_format: ${{ needs.lint_and_format.result }}"
      - run: echo "State of test: ${{ needs.test.result }}"
